//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chat_rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class friend_Relations
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public int friend_ID { get; set; }
        public int Relation_Type { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
